String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});
(function(){function q(e,d){var h=p(e);$("#aft").val(e).select();$("#aft").parent().addClass("large").removeClass("hide");$("#bef").parent().addClass("small");var c=d-h;1024>d?($("#befB").text(d+" B"),$("#aftB").text(h+" B"),$("#minus").text(d===h?"\u00b10B(0%)":"-"+c+" B("+(100-h/d*100).toFixed(2)+"%)")):($("#befB").text((0|d/1024)+" KB("+d+" B)"),$("#aftB").text((0|h/1024)+" KB("+h+" B)"),$("#minus").text(d===h?"\u00b10B(0%)":"-"+(0|c/1024)+" KB("+c+" B)("+(100-h/d*100).toFixed(2)+"%)"));$("#mes").stop(!0,
!1).addClass("on").css("opacity","1").fadeTo(1500,.3,function(){$(this).removeClass("on")})}var p=function(e){for(var d=0,h=0,c=e.length;h<c;)d+=4>escape(e.charAt(h)).length?1:2,h+=1;return d},n={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aquamarine:"#7fffd4",black:"#000",blanchedalmond:"#ffebcd",blueviolet:"#8a2be2",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",
darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#f0f",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",goldenrod:"#daa520",greenyellow:"#adff2f",
honeydew:"#f0fff0",indianred:"#cd5c5c",lavendar:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#789",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",limegreen:"#32cd32",magenta:"#f0f",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",
mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",olivedrab:"#6b8e23",orangered:"#ff4500",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhite:"#ffefd5",peachpuff:"#ffdab9",powderblue:"#b0e0e6",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",
sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",slateblue:"#6a5acd",slategray:"#708090",springgreen:"#00ff7f",steelblue:"#4682b4",turquoise:"#40e0d0",white:"#fff",whitesmoke:"#f5f5f5",yellow:"#ff0",yellowgreen:"#9acd32","#f0ffff":"azure","#f5f5dc":"beige","#ffe4c4":"bisque","#a52a2a":"brown","#ff7f50":"coral","#ffd700":"gold","#808080":"gray","#008000":"green","#4b0082":"indigo","#fffff0":"ivory","#f0e68c":"khaki","#faf0e6":"linen","#800000":"maroon","#000080":"navy","#808000":"olive",
"#ffa500":"orange","#da70d6":"orchid","#cd853f":"peru","#ffc0cb":"pink","#dda0dd":"plum","#800080":"purple","#ff0000":"red","#f00":"red","#fa8072":"salmon","#a0522d":"sienna","#c0c0c0":"silver","#fffafa":"snow","#d2b48c":"tan","#008080":"teal","#ff6347":"tomato","#ee82ee":"violet","#f5deb3":"wheat"},m=window.Compressors={optimizeColorName:function(){var e=cssBlock.original.toLowerCase(),d;for(d in n)-1!==e.indexOf(d)&&cssBlock.selector(1).replace(new RegExp("(^|[\\(\\[, ])"+d+"([ \\]\\),;]|$)","i"),
"$1"+n[d]+"$2")},clearZeroUnit:function(){cssBlock.selector(1).replace(/(\D)[0](?:em|px|%)/g,"$10")},clearZero:function(){cssBlock.selector(1).replace(/(^|[\D])0\.(\d)/g,"$1.$2")},clearComments:function(){cssBlock.selector(6).del()},colorCodeToLowerCase:function(e){cssBlock.selector(1).replace(/(#[0-9a-fA-F][0-9a-fA-F]?[0-9a-fA-F][0-9a-fA-F]?[0-9a-fA-F][0-9a-fA-F]?)/g,function(d,e){return e.toLowerCase()})},noneToZero:function(e){var d=cssBlock.getBlock(),h=0;for(e=d.length;h<e;h++)1==d[h][2]&&(d[h][0]=
d[h][0].replace(/[\s\S]+/g,function(c){var b=d[h-2][0];return-1!=b.indexOf("background-image")?c:-1!=b.indexOf("border")||-1!=b.indexOf("background")||-1!=b.indexOf("outline")?c.replace(/none/g,"0"):c}),cssBlock.setBlock(h,d[h]))},optimizeMargin:function(e){return m.optimizePM(e,"margin")},optimizePadding:function(e){return m.optimizePM(e,"padding")},optimizePM:function(e,d){for(var h=cssBlock.getBlock(),c=[],b=h.length;b--;){if(2==h[b][1]&&4==f.ok){var f=f.right==f.left?f.top==f.bottom?f.top==f.right?
f.top:f.top+" "+f.right:f.top+" "+f.right+" "+f.bottom:f.top+" "+f.right+" "+f.bottom+" "+f.left,a=l.shift(),g=cssBlock.getBlock()[a];g[0]=d;cssBlock.setBlock(a,g);g=cssBlock.getBlock()[a+2];-1!==g[0].indexOf(";")?g[0]=f+";":g[0]=f;cssBlock.setBlock(a+2,g);var c=c.concat(l),f={top:null,bottom:null,right:null,left:null,ok:0},l=[]}3==h[b][1]&&(f={top:null,bottom:null,right:null,left:null,ok:0},l=[]);1==h[b][1]&&(g=h[b-2][0].trim(),a=h[b][0],8==h[b-2][1]&&(0===g.indexOf(d)&&l.push(b-2),0===g.indexOf(d)&&
4>f.ok&&(g==d?(a=a.replace(/;/g,"").split(" "),g=a.length,5<=g?error("padding has 5 values."):0==g?error("padding has no value."):(null===f.top&&(f.top=a[0]),null===f.right&&(f.right=1===g?a[0]:a[1]),null===f.bottom&&(f.bottom=3===g||4===g?a[2]:a[0]),null===f.left&&(f.left=2===g||3===g?a[1]:4===g?a[3]:a[0])),f.ok=4):0===g.indexOf(d+"-")&&(g=g.split(d+"-")[1],"top"!==g&&"right"!==g&&"bottom"!==g&&"left"!==g||null!==f[g]||(f.ok++,f[g]=a)))))}b=0;for(h=c.length;b<h;b++)console.log(cssBlock.joinBlock()),
cssBlock.deleteBlock(c[b]),cssBlock.deleteBlock(c[b]+1),cssBlock.deleteBlock(c[b]+2),console.log(cssBlock.joinBlock())},compress:function(e){var d=$("#bef").val(),h=p(d);cssBlock.init(d);e.comment&&m.clearComments(d);e.zero&&m.clearZeroUnit(d);e.decimals&&m.clearZero(d);if(!e.option||e.indent){for(var c=cssBlock.selector(4),b=0,f=c.length;b<f;b++){var a=cssBlock.getBlock()[c[b][2]+1];a[0]=a[0].replace(/^[\t ]*/g,"");cssBlock.setBlock(c[b][2]+1,a)}a=cssBlock.getBlock()[0];a[0]=a[0].replace(/^[\t ]*/g,
"");cssBlock.setBlock(0,a)}e.option&&!e.line||cssBlock.selector(4).del();if(!e.option||e.comma)cssBlock.selector(0).replace(/[\t ]*,[\t ]*/g,","),cssBlock.selector(1).replace(/[\t ]*,[\t ]*/g,",");for(var g=["colon","sc_bracket","ec_bracket"],l=0,n=g.length;l<n;l++)if(!e.option||e[g[l]])for("colon"==g[l]&&(c=cssBlock.selector(9)),"sc_bracket"==g[l]&&(c=cssBlock.selector(2)),"ec_bracket"==g[l]&&(c=cssBlock.selector(3)),b=0,f=c.length;b<f;b++){0<=c[b][2]-1&&(a=cssBlock.getBlock()[c[b][2]-1],a[0]=a[0].replace(/[\t ]*$/g,
""),cssBlock.setBlock(c[b][2]-1,a));for(var k=1,a=cssBlock.getBlock();c[b][2]+k<=a.length-1&&(5==a[c[b][2]+k][1]||4==a[c[b][2]+k][1]);)k++;delete a;cssBlock.getBlock().length-1>=c[b][2]+k&&(a=cssBlock.getBlock()[c[b][2]+k],a[0]=a[0].replace(/^[\t ]*?([^\t ])/g,"$1"),cssBlock.setBlock(c[b][2]+k,a))}delete g;if(!e.option||e.semicolon)for(c=cssBlock.selector(1),b=0,f=c.length;b<f;b++)if(-1!==c[b][0].indexOf(";")){a=c[b];a[0]=a[0].replace(/[\t ]*;[\t ]*$/,";");cssBlock.setBlock(c[b][2],a);k=1;for(a=cssBlock.getBlock();c[b][2]+
k<=a.length-1&&(5==a[c[b][2]+k][1]||4==a[c[b][2]+k][1]);)k++;delete a;a=cssBlock.getBlock()[c[b][2]+k];a[0]=a[0].replace(/^[\t ]*?([^\t ])/,"$1");cssBlock.setBlock(c[b][2]+k,a)}if(!e.option||e.needlessSemi)for(c=cssBlock.selector(3),b=0,f=c.length;b<f;b++){a=cssBlock.getBlock();for(k=1;a.length-1>=c[b][2]-k&&(5==a[c[b][2]-k][1]||4==a[c[b][2]-k][1]);)k++;delete a;a=cssBlock.getBlock()[c[b][2]-k];a[0]=a[0].replace(/[\t ]*;[\t ]*$/,"");cssBlock.setBlock(c[b][2]-k,a)}e.option&&!e.important||cssBlock.selector(1).replace(/[\t ]*(?:!important)[\t ]*/g,
"!important");e.color_name&&m.optimizeColorName(d);e.padding&&-1!==d.indexOf("padding")&&m.optimizePadding(d);e.margin&&-1!==d.indexOf("margin")&&m.optimizeMargin(d);e.color&&cssBlock.selector(1).replace(/\#([0-9a-fA-F])\1([0-9a-fA-F])\2([0-9a-fA-F])\3/g,"#$1$2$3");e.lower&&m.colorCodeToLowerCase(d);e.none&&m.noneToZero(d);q(cssBlock.joinBlock(),h)}}})();
