(function(g){var a=g({});g.subscribe=function(){a.on.apply(a,arguments)};g.unsubscribe=function(){a.off.apply(a,arguments)};g.publish=function(){a.trigger.apply(a,arguments)}})(jQuery);
(function(g,a){function w(g,e){var d=u(g);a("#aft").val(g).select();a("#aft").parent().addClass("large").removeClass("hide");a("#bef").parent().addClass("small");var c=e-d;1024>e?(a("#befB").text(e+" B"),a("#aftB").text(d+" B"),a("#minus").text(e===d?"\u00b10B(0%)":"-"+c+" B("+(100-d/e*100).toFixed(2)+"%)")):(a("#befB").text((0|e/1024)+" KB("+e+" B)"),a("#aftB").text((0|d/1024)+" KB("+d+" B)"),a("#minus").text(e===d?"\u00b10B(0%)":"-"+(0|c/1024)+" KB("+c+" B)("+(100-d/e*100).toFixed(2)+"%)"));a("#mes").stop(!0,
!1).addClass("on").css("opacity","1").fadeTo(1500,.3,function(){a(this).removeClass("on")})}function u(a){for(var e=0,d=0,c=a.length;d<c;)e+=4>escape(a.charAt(d)).length?1:2,d+=1;return e}a(function(){a("body").on("dragover",function(a){a.preventDefault();a.stopPropagation();return!1});Array.prototype.has=function(a){var b=0,c=this.length-1,d;if(this[this.length-1]<a)return!1;for(;b<=c;)if(d=0|(b+c)/2,this[d]>a&&(c=d-1),this[d]<a&&(b=d+1),this[d]==a)return!0;return!1};var x=a("#rform"),e=a("#lform"),
d=a("#compress"),c=a("#options"),h=a("input"),k=a("select"),p=a("#option_menu"),s=a("#option"),y=a("#option_all"),q=g.document,r=!0,m,l,b,f,n,v,t=function(a){var b="",c="";return 0<q.cookie.length&&(b=q.cookie.indexOf(a+"="),-1!=b)?(b=b+a.length+1,c=q.cookie.indexOf(";",b),-1==c&&(c=q.cookie.length),unescape(q.cookie.substring(b,c))):!1};if(!1!==JSON.parse(t("input_option"))){m=JSON.parse(t("input_option"));l=JSON.parse(t("select_option"));b=0;for(f=h.length;b<f;b+=1)h.eq(b).attr("checked",!!m[h.eq(b).attr("id")]);
b=0;for(f=k.length;b<f;b+=1)l[k.eq(b).attr("id")]&&k.eq(b).val(l[k.eq(b).attr("id")])}else{m={};l={};b=0;for(f=h.length;b<f;b+=1)m[h.eq(b).attr("id")]=!!h.eq(b).attr("checked");b=0;for(f=k.length;b<f;b+=1)l[k.eq(b).attr("id")]=k.eq(b).find("option:selected").val()}s.attr("checked")?p.show():c.css("border-left","3px solid #CCC");x.css3form();n=p.find("div.customCheckBox").find("a");v=n.css("width");p.css("width");c.finda=function(a){return c.find("a").eq(a.index("input[type='checkbox']"))};!0==!!a("#HackMode").attr("checked")?
(c.finda(a("#padding").attr("disabled",!0)).addClass("Hack"),c.finda(a("#margin").attr("disabled",!0)).addClass("Hack")):(c.finda(a("#padding").attr("disabled",!1)).removeClass("Hack"),c.finda(a("#margin").attr("disabled",!1)).removeClass("Hack"));a("#HackMode").on("click",function(){!0==!a("#HackMode").attr("checked")?(c.finda(a("#padding").attr("disabled",!0)).addClass("Hack"),c.finda(a("#margin").attr("disabled",!0)).addClass("Hack")):(c.finda(a("#padding").attr("disabled",!1)).removeClass("Hack"),
c.finda(a("#margin").attr("disabled",!1)).removeClass("Hack"))});e.find(".select , .reset").on("click",function(b){a(this).siblings("textarea").select()}).end().find("#bef").select();d.on("click",function(b){b.preventDefault();b.stopPropagation();b=0;for(var c=h.length;b<c;b+=1)m[h.eq(b).attr("id")]=h.eq(b).attr("checked")&&!h.eq(b).is(":disabled");b=u(a("#bef").val());c=Compressors.compress(m,a("#bef").val());w(c.joinBlock(),b)});a("#bef,#aft").on("focus",function(){var b=a(this).attr("id");a(this).parent().hasClass("small")&&
(a(this).parent().removeClass("large small").addClass("large"),a("bef"==b?"#aft":"#bef").parent().removeClass("large small").addClass("small"))});if(g.File)a("#bef").on("dragenter",function(a){a.preventDefault();a.stopPropagation()}).on("dragover",function(a){a.originalEvent.dataTransfer.dropEffect="copy";a.preventDefault();a.stopPropagation()}).on("drop",function(c){c.preventDefault();c.stopPropagation();c=c.originalEvent;c=c.dataTransfer.files;l.encode=k.filter("#encode").find("option:selected").val();
b=0;for(f=c.length;b<f;b+=1){var e=new FileReader;e.readAsText(c[b],l.encode);e.onload=a.proxy(function(){a(this).val(e.result);d.trigger("click")},this)}});else a("#bef").attr("placeholder","\u3053\u3053\u306b\u30b3\u30fc\u30c9\u3092\u30da\u30fc\u30b9\u30c8\u3057\u3066\u304f\u3060\u3055\u3044\u3002\u3069\u3046\u3084\u3089\u304a\u4f7f\u3044\u306e\u30d6\u30e9\u30a6\u30b6\u3067\u306f\u30c9\u30e9\u30c3\u30b0\u30a2\u30f3\u30c9\u30c9\u30ed\u30c3\u30d7\u306f\u5bfe\u5fdc\u3057\u3066\u3044\u306a\u3044\u3088\u3046\u3067\u3059\u3002");
a(g).on("keydown",function(b){if(68===b.keyCode&&b.shiftKey&&(b.ctrlKey&&!b.metaKey||!b.ctrlKey&&b.metaKey)&&b.altKey)return b.preventDefault(),a.publish("debug-start"),!1;(b.ctrlKery&&!b.metaKey||!b.ctrlKey&&b.metaKey)&&13===b.keyCode&&d.trigger("click")});s.on("click",function(a){n.is(":animated")||p.is(":animated")||(s.attr("checked")?(p.hide(),c.css("border-left","3px solid #CCC"),n.show().css("width",v)):(p.show(),c.css("border-left","none")))});y.on("click",function(a){if(n.is(":visible"))for(r=
!r,b=0,f=n.length;b<f;b+=1)(r&&!n.eq(b).hasClass("checked")||!r&&n.eq(b).hasClass("checked"))&&n.eq(b).click()});a("#save").on("click",function(a){m={};l={};b=0;for(f=h.length;b<f;b+=1)m[h.eq(b).attr("id")]=!!h.eq(b).attr("checked");b=0;for(f=k.length;b<f;b+=1)l[k.eq(b).attr("id")]=k.eq(b).find("option:selected").val();a={input_option:JSON.stringify(m),select_option:JSON.stringify(l)};var c=location.pathname,d=c.split("/");""!=d[d.length-1]&&(d[d.length-1]="",c=d.join("/"));var d=(new Date).getTime(),
d=(new Date(d+6048E5)).toUTCString(),e="",g;for(g in a)value=a[g],e+=g+"="+escape(value)+";";e=e+("path="+c+";")+("expires="+d+";");q.cookie=e});a("#wrench").on("click",function(b){b.preventDefault();b.stopPropagation();c.toggle();a("#results").toggle()});a("#compare").on("click",function(){event.preventDefault();event.stopPropagation();a("<form>").attr({method:"POST",action:"http://difff.jp",target:"_blank"}).append(a("<textarea>").val(a("#bef").val()).attr("name","sequenceA")).append(a("<textarea>").val(a("#aft").val()).attr("name",
"sequenceB")).submit()});a.subscribe("debug-start",function(){c.find(".customCheckBox").find("a");a("body").addClass("debug");var b=[".white-space{\n\twhite-space: nowrap;\n\tbackground :#FFF!important;\n\tcolor : #FFFFFF !important ;\n\t margin:3px 3px 5px 3px;\n}\n@media screen and (max-device-width:480px){\n\t.black , .button {\n\tbackground:none;\n\tbackground-image:none;\n\t color:black;/*OK*/\n\t margin: 0px;\n\t opacity:0.9;\n\t padding:3px 3px 3px 3px;\n\t}\n}",".white-space{\n\twhite-space: nowrap;\n\tbackground :#FFF!important;\n\tcolor : #FFFFFF !important ;\n\t margin:3px 3px 5px 3px;\npadding:10px;\npadding-left:30px;\npadding-right:30px;\n}\n@media screen and (max-device-width:480px){\n\t.black , .button {\n\tbackground:none;\n\tbackground-image:none;\n\t color:black;/*OK*/\n\t margin: 0px;\n\t opacity:0.9;\n\t padding:3px 3px 3px 3px;\n\t}\n}"],
d=[".white-space{white-space:nowrap;background:#fff!important;color:#fff!important;margin:3px 3px 5px}@media screen and (max-device-width:480px){.black,.button{background:none;background-image:none;color:#000;margin:0;opacity:.9;padding:3px}}",".white-space{white-space:nowrap;background:#fff!important;color:#fff!important;margin:3px 3px 5px;padding:10px 30px}@media screen and (max-device-width:480px){.black,.button{background:none;background-image:none;color:#000;margin:0;opacity:.9;padding:3px}}"];
a("#bef").val(b[0]);a("#compress").trigger("click");setTimeout(function(){console.log(a("#aft").val()==d[0]);a("#bef").val(b[1]);a("#compress").trigger("click");setTimeout(function(){console.log(a("#aft").val()==d[1])})},10)});a("#body").children().css("display","block")})})(this,jQuery);
